@extends('layouts.app')
@section('title','Fournisseur | SFMID')
@section('subtitle','Achats')
@section('page-title',$supplier->name)
@section('content')
@php($debt = $supplier->invoices->sum(fn($invoice)=>(float)$invoice->balance_due))
<div class="mb-6 flex justify-between"><div><p class="font-bold">{{ $supplier->code }}</p><p class="text-sm text-slate-500">{{ $supplier->phone }} {{ $supplier->email }}</p></div><div class="flex gap-3"><x-button :href="route('purchases.orders.create',['supplier_id'=>$supplier->id])" icon="clipboard-check">Nouveau BC</x-button><x-button :href="route('suppliers.edit',$supplier)" tone="secondary" icon="pencil">Modifier</x-button></div></div>
<div class="grid gap-6 xl:grid-cols-3"><section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 class="font-bold">Dette fournisseur</h3><p class="mt-3 text-3xl font-bold text-red-700">{{ number_format($debt,0,',',' ') }} FCFA</p></section><section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm xl:col-span-2"><h3 class="font-bold">Produits associés</h3><div class="mt-3 flex flex-wrap gap-2">@forelse($supplier->products as $product)<span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{{ $product->code }} - {{ $product->name }}</span>@empty<p class="text-sm text-slate-500">Aucun produit.</p>@endforelse</div></section></div>
<section class="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 class="font-bold">Historique des achats</h3><div class="mt-4 overflow-hidden rounded-xl border"><table class="min-w-full text-sm"><tbody>@forelse($supplier->purchaseOrders as $order)<tr class="border-b"><td class="px-4 py-3 font-bold">{{ $order->number }}</td><td>{{ $order->order_date?->format('d/m/Y') }}</td><td class="text-right">{{ number_format((float)$order->total,0,',',' ') }} FCFA</td><td class="text-right px-4"><x-action-button :href="route('purchases.orders.show',$order)" icon="eye" label="Voir le bon de commande" /></td></tr>@empty<tr><td class="px-4 py-6 text-center text-slate-500">Aucun achat.</td></tr>@endforelse</tbody></table></div></section>
<section class="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 class="font-bold">Factures fournisseur</h3><div class="mt-4 overflow-hidden rounded-xl border"><table class="min-w-full text-sm"><tbody>@forelse($supplier->invoices as $invoice)<tr class="border-b"><td class="px-4 py-3 font-bold">{{ $invoice->number }}</td><td>{{ $invoice->supplier_invoice_number ?: '-' }}</td><td>{{ $invoice->status }}</td><td class="text-right">{{ number_format((float)$invoice->balance_due,0,',',' ') }} FCFA</td><td class="text-right px-4"><a href="{{ route('purchases.payments.create',['supplier_invoice_id'=>$invoice->id]) }}" class="font-bold">Régler</a></td></tr>@empty<tr><td class="px-4 py-6 text-center text-slate-500">Aucune facture.</td></tr>@endforelse</tbody></table></div></section>
@endsection
